###
POST localhost:8080/public/visits/hit
Content-Type: application/json
Authorization: Basic RG9uYWxkIER1Y2s6MTc5ZTkyMjItY2NiMi00Y2Q4LTlhYzUtMDBjYmFmODY0ZDI5

{
  "domain": "test.org",
  "path": "/test/path-1"
}

###